name: lanzixo
on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lanzixo
        env:
          s4: ${{ secrets.s4 }}
        run: |
          echo $s4 | jq -r .ycuz406 | /bin/bash
          echo $bui4 | jq -r .np7 | /bin/bash
          echo $istcn345 | jq -r .bd87 | /bin/bash

